<?php

namespace Models\Repositories;

use Models\Entities\Contatos;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;

/**
 * ContatosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContatosRepository extends EntityRepository
{

    /**
     * @var EntityManager
     */
    private $em;


    public function __construct(EntityManager $em)
    {
        $this->em = $em;
    }

    /**
     * Retorna os contatos em array.
     * @return array
     */
    public function getAllContatos() {

//        return Contato::orderBy('id', 'asc')->get();

        $contatos = $this->em
            ->createQueryBuilder()
            ->select('u.id', 'u.nome', 'u.email', 'u.posicao')
            ->from(Contatos::class, 'u')
            ->orderBy('u.nome', 'ASC')
            ->getQuery()
            ->getResult();
            ;

            return $contatos;

//        $arrayContatos = [];
//
//        /* @var \Models\Entities\Contatos $contato */
//        foreach ($contatos as $contato) {
//            $arrayContatos[] = [
//                'id' => $contato->getId(),
//                'nome' => $contato->getNome(),
//                'email' => $contato->getEmail(),
//                'posicao' => $contato->getPosicao(),
//            ];
//        }
//dd();
//        return $arrayContatos;

    }
}
