<?php

namespace Models\Repositories;

use Models\Entities\Contatos;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;

/**
 * ContatosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContatosRepository extends EntityRepository
{

    /**
     * @var EntityManager
     */
    private $em;


    public function __construct(EntityManager $em)
    {
        $this->em = $em;
    }

    /**
     * Retorna os contatos em array.
     * @return array
     */
    public function getAllContatos() {

//        return Contato::orderBy('id', 'asc')->get();

        $contatos = $this->em
            ->createQueryBuilder()
            ->select('u.id', 'u.nome', 'u.email', 'u.telefone', 'u.posicao')
            ->from(Contatos::class, 'u')
            ->orderBy('u.nome', 'ASC')
            ->getQuery()
            ->getResult();
            ;

            return $contatos;

    }

    /**
     * Return of contatos by Id.
     * @param $id
     * @return array
     */
    public function findById($id)
    {
        $contato = $this->em
            ->createQueryBuilder()
            ->select('u.id', 'u.nome', 'u.email', 'u.telefone', 'u.posicao')
            ->from(Contatos::class, 'u')
            ->where('u.id = ' . $id)
            ->getQuery()
            ->getResult();
        ;
        return $contato[0];
    }

}
