<?php

namespace Models\Repositories;

use Models\Entities\Users;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends EntityRepository
{
    /**
     * @var EntityManager
     */
    private $em;


    public function __construct(EntityManager $em)
    {
        $this->em = $em;
    }

    public function getAllUsers()
    {
        return $this->em
            ->createQueryBuilder()
            ->select('u.id', 'u.name', 'u.email', 'u.password')
            ->from(Users::class, 'u')
            ->orderBy('u.name', 'ASC')
            ->getQuery()
            ->getResult();
            ;

    }

}
